# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
في :
 سلسلة من المهام التي سيتم تنفيذها كجزء من الوظيفة
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # ينفذ أمرًا واحدًا غلاف غلاف العدائين


      # يدير مجموعة من الأوامر باستخدام غلاف العدائين
      - name: Run a multi-line script
        run: |
          صدى إضافة إجراءات أخرى لبناء j
